# These are the standard keywords output by twistedActor
# Add them to any actor dictionary based on twistedActor
    Key("text",
        String(),
        help = "Text message",
    ),
    Key("yourUserID",
        Int(),
        help = "Your user ID number; use this to recognize replies triggered by your commands; never 0",
    ),
    Key("numUsers",
        Int(),
        help = "Number of connected users",
    ),
    Key("userInfo",
        Int(help = "user ID"),
        Str(help = "socket address"),
        help = "Basic information about one user",
    ),
    Key("unknownCommand",
        String(help = "command verb"),
        help = "The command verb (the first word of your command string) is not supported by this actor",
    ),
    Key("version",
        String(invalid="?"),
        help = "The version of the actor",
    ),
    Key("refCount",
        Int(help = "refcount"),
        String(help = "object"),
        help = "The reference count for an object",
    ),
    
    # you must make a copy of the following keyword for each device
    Key("<dev>ConnState", 
        Enum("Connecting", "Authorizing", "Connected", 
            "Disconnecting", "Disconnected", "Failing", "Failed",
            help = "Connection State"
        ),
        String(help = "Reason"),
        help =  "State of connection to the device",
    ),
